const RECIPES=[
{id:'r1',name:'Protein Oatmeal',category:'Breakfast',time:'10 min',prep:'3 min',cook:'7 min',calories:430,protein:35,carbs:55,fat:9,desc:'Creamy oats with Greek yogurt, berries and protein.',tip:'Let the oats cool for one minute before adding protein powder to prevent clumps.',image:'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&w=900&q=80',ingredients:['60 g rolled oats','170 g nonfat Greek yogurt','1 scoop protein powder','100 g berries','240 ml water or milk','Pinch of salt'],steps:['Add the oats, liquid and salt to a small saucepan and bring to a gentle simmer over medium heat.','Cook for 5–7 minutes, stirring every minute, until the oats are creamy and most of the liquid is absorbed.','Remove from the heat, wait one minute, then mix in the protein powder; add a splash of liquid if it becomes too thick.','Transfer to a bowl and finish with Greek yogurt and berries.']},
{id:'r2',name:'Egg & Potato Breakfast',category:'Breakfast',time:'25 min',prep:'7 min',cook:'18 min',calories:500,protein:32,carbs:46,fat:21,desc:'A filling savory breakfast with eggs and crisp potatoes.',tip:'Cut the potatoes into 1 cm cubes so they cook evenly and become crisp.',image:'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=900&q=80',ingredients:['2 whole eggs','150 g egg whites','250 g potatoes','30 g shredded cheese','1 tsp olive oil','Salt, pepper and paprika'],steps:['Cut the potatoes into 1 cm cubes, rinse them, and pat completely dry.','Heat the oil in a nonstick skillet over medium-high heat; cook the potatoes for 12–15 minutes, turning occasionally, until tender and browned.','Lower the heat to medium, move the potatoes to one side, and pour in the beaten eggs and egg whites. Stir gently until almost set.','Fold everything together, add the cheese and seasoning, cover for one minute, and serve hot.']},
{id:'r3',name:'Chicken Burrito Bowl',category:'Lunch',time:'30 min',prep:'10 min',cook:'20 min',calories:610,protein:52,carbs:67,fat:16,desc:'Meal-prep friendly chicken, rice, beans and fresh toppings.',tip:'Keep salsa and avocado separate until serving if preparing several portions.',image:'https://hips.hearstapps.com/hmg-prod/images/copycat-chipotle-burrito-bowl-secondary-641dd68c6847f.jpg?crop=1xw:1xh;center,top&resize=980:*',ingredients:['170 g chicken breast','180 g cooked rice','80 g black beans','60 g salsa','50 g avocado','1 tsp taco seasoning'],steps:['Coat the chicken with taco seasoning and cook in a hot skillet for 5–7 minutes per side, until the center reaches 74°C / 165°F.','Rest the chicken for five minutes before slicing so it stays juicy.','Warm the rice and rinsed black beans, then layer them in a bowl.','Add the sliced chicken, salsa and avocado; season with lime or cilantro if desired.']},
{id:'r4',name:'Turkey Rice Skillet',category:'Lunch',time:'25 min',prep:'5 min',cook:'20 min',calories:540,protein:48,carbs:58,fat:13,desc:'Lean turkey, rice and vegetables in one easy skillet.',tip:'Use chilled cooked rice for the best texture and to prevent sticking.',image:'https://media.hellofresh.com/w_750,q_auto,f_auto,c_limit,fl_lossy/hellofresh_s3/67d084401f2b114070d2e76a/step-5a24c820.jpg',ingredients:['170 g lean ground turkey','170 g cooked rice','150 g mixed vegetables','30 g tomato sauce','1 tsp olive oil','Garlic, salt and pepper'],steps:['Heat the oil in a large skillet over medium-high heat and brown the turkey for 6–8 minutes, breaking it into small pieces.','Add the vegetables and garlic; cook for 4–5 minutes until the vegetables are tender-crisp.','Stir in the tomato sauce and two tablespoons of water, then simmer for two minutes.','Fold in the cooked rice and heat for 3–4 minutes; season to taste before serving.']},
{id:'r5',name:'High Protein Pasta',category:'Dinner',time:'30 min',prep:'8 min',cook:'22 min',calories:680,protein:61,carbs:72,fat:17,desc:'Comfort-food pasta built around a high-protein serving.',tip:'Reserve pasta water before draining; its starch helps the sauce coat the pasta.',image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80',ingredients:['100 g dry pasta','170 g chicken breast','150 g tomato sauce','15 g parmesan','60 g spinach','Salt, pepper and Italian herbs'],steps:['Boil the pasta in salted water until al dente; reserve 120 ml of pasta water before draining.','Season the chicken and cook over medium-high heat for 5–7 minutes per side, then rest and slice it.','Warm the tomato sauce in the same pan, add the spinach, and stir until wilted.','Add the pasta and enough reserved water to loosen the sauce; fold in the chicken and finish with parmesan.']},
{id:'r6',name:'Salmon Potato Plate',category:'Dinner',time:'35 min',prep:'8 min',cook:'27 min',calories:585,protein:44,carbs:51,fat:23,desc:'Simple salmon, roasted potatoes and vegetables.',tip:'Start the potatoes first; add the salmon during the final 12–14 minutes.',image:'https://www.averiecooks.com/wp-content/uploads/2022/12/Sheet-Pan-Lemon-Dijon-Baked-Salmon-and-Potatoes.png',ingredients:['170 g salmon','250 g potatoes','150 g green vegetables','1 tsp olive oil','1/2 lemon','Salt, pepper and garlic powder'],steps:['Heat the oven to 220°C / 425°F. Cut the potatoes into 2 cm pieces and toss with half the oil and seasoning.','Roast the potatoes for 15 minutes, turn them, and move them to one side of the tray.','Add the seasoned salmon and vegetables, drizzle with the remaining oil, and roast for 12–14 minutes.','Check that the salmon flakes easily, squeeze lemon over the tray, and serve immediately.']},
{id:'r7',name:'Strawberry Protein Shake',category:'Shake',time:'5 min',prep:'5 min',cook:'0 min',calories:410,protein:46,carbs:44,fat:8,desc:'A fast protein shake for breakfast or after training.',tip:'Blend the liquid first and the ice last to protect the blender blades.',image:'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=900&q=80',ingredients:['1 scoop protein powder','250 ml milk','150 g strawberries','100 g Greek yogurt','5–6 ice cubes'],steps:['Pour the milk into the blender first, followed by the yogurt and protein powder.','Add the strawberries and ice cubes.','Blend on low for 15 seconds, then on high for 30–45 seconds until completely smooth.','Taste and adjust the thickness with a small amount of water or additional ice.']},
{id:'r8',name:'Protein Pancakes',category:'Breakfast',time:'20 min',prep:'7 min',cook:'13 min',calories:445,protein:38,carbs:48,fat:11,desc:'Fluffy oat pancakes with banana and a high-protein batter.',tip:'Wait until bubbles form and the edges look dry before flipping.',image:'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=900&q=80',ingredients:['60 g rolled oats','1 medium banana','1 whole egg','120 g egg whites','1/2 scoop protein powder','1 tsp baking powder'],steps:['Blend the oats into flour, then add the banana, egg, egg whites, protein powder and baking powder.','Blend just until smooth and let the batter rest for three minutes.','Heat a nonstick skillet over medium-low heat and lightly coat it with cooking spray.','Pour small pancakes and cook for 2–3 minutes per side; serve with fruit or yogurt.']},
{id:'r9',name:'Greek Yogurt Crunch Bowl',category:'Breakfast',time:'5 min',prep:'5 min',cook:'0 min',calories:390,protein:33,carbs:45,fat:9,desc:'A quick yogurt bowl with fruit, oats and a satisfying crunch.',tip:'Assemble just before eating so the granola stays crisp.',image:'https://images.unsplash.com/photo-1511690656952-34342bb7c2f2?auto=format&fit=crop&w=900&q=80',ingredients:['250 g Greek yogurt','100 g mixed berries','35 g granola','10 g honey','10 g chia seeds'],steps:['Spread the Greek yogurt evenly in a wide bowl.','Wash and dry the berries, then arrange them over the yogurt.','Add the granola and chia seeds in separate sections for an even texture.','Drizzle with honey immediately before serving.']},
{id:'r10',name:'Mediterranean Tuna Wrap',category:'Lunch',time:'12 min',prep:'12 min',cook:'0 min',calories:475,protein:42,carbs:45,fat:14,desc:'A fresh tuna wrap with yogurt dressing and crunchy vegetables.',tip:'Drain the tuna thoroughly so the tortilla does not become soggy.',image:'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80',ingredients:['1 large whole-wheat tortilla','140 g tuna in water, drained','40 g Greek yogurt','80 g cucumber and tomato','20 g feta cheese','Lemon, pepper and herbs'],steps:['Mix the drained tuna with Greek yogurt, lemon juice, pepper and herbs.','Warm the tortilla for 15 seconds so it folds without tearing.','Place the tuna mixture down the center and add the chopped vegetables and feta.','Fold in both sides, roll tightly, and slice in half.']},
{id:'r11',name:'Beef Vegetable Stir-Fry',category:'Dinner',time:'25 min',prep:'10 min',cook:'15 min',calories:560,protein:47,carbs:55,fat:17,desc:'Lean beef and crisp vegetables in a savory ginger sauce.',tip:'Cook in two batches if the pan is small; crowding causes steaming.',image:'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=80',ingredients:['170 g lean beef strips','170 g cooked rice','200 g stir-fry vegetables','15 ml low-sodium soy sauce','1 tsp sesame oil','Garlic and fresh ginger'],steps:['Pat the beef dry and slice it thinly against the grain. Mix the sauce ingredients separately.','Heat half the oil in a very hot skillet and sear the beef for 2–3 minutes; transfer it to a plate.','Add the remaining oil and vegetables, cooking for 4–5 minutes while keeping them crisp.','Return the beef, add the sauce, toss for one minute, and serve over hot rice.']},
{id:'r12',name:'Chicken Pesto Couscous',category:'Dinner',time:'28 min',prep:'8 min',cook:'20 min',calories:625,protein:54,carbs:62,fat:18,desc:'Juicy chicken, couscous and vegetables finished with pesto.',tip:'Fluff couscous with a fork instead of stirring to keep the grains separate.',image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80',ingredients:['170 g chicken breast','75 g dry couscous','150 g zucchini and tomatoes','20 g basil pesto','200 ml chicken broth','Salt and pepper'],steps:['Season the chicken and cook in a skillet for 5–7 minutes per side; rest it before slicing.','Bring the broth to a boil, stir in the couscous, cover, remove from heat, and rest for five minutes.','Sauté the zucchini and tomatoes for 4–5 minutes until lightly browned.','Fluff the couscous, fold in pesto and vegetables, and top with sliced chicken.']},
{id:'r13',name:'Chocolate Banana Shake',category:'Shake',time:'5 min',prep:'5 min',cook:'0 min',calories:455,protein:43,carbs:52,fat:10,desc:'A thick chocolate shake with banana, cocoa and peanut butter.',tip:'Use a frozen banana for a thicker shake without adding extra ice.',image:'https://images.unsplash.com/photo-1577805947697-89e18249d767?auto=format&fit=crop&w=900&q=80',ingredients:['1 scoop chocolate protein powder','250 ml milk','1 frozen banana','10 g peanut butter','5 g cocoa powder','Pinch of salt'],steps:['Add the milk to the blender, followed by protein powder and cocoa.','Add the frozen banana, peanut butter and salt.','Blend for 45–60 seconds, stopping once to scrape the sides if needed.','Add a splash of milk for a thinner texture and serve immediately.']},
{id:'r14',name:'Shrimp Taco Plate',category:'Lunch',time:'22 min',prep:'12 min',cook:'10 min',calories:520,protein:41,carbs:58,fat:15,desc:'Spiced shrimp tacos with cabbage, avocado and lime crema.',tip:'Dry the shrimp well before seasoning so they sear instead of steaming.',image:'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=900&q=80',ingredients:['170 g peeled shrimp','3 corn tortillas','100 g shredded cabbage','50 g avocado','40 g Greek yogurt','Lime, chili powder and cumin'],steps:['Pat the shrimp dry and season with chili powder, cumin and salt. Mix yogurt with lime juice for the crema.','Heat a skillet over medium-high heat and cook the shrimp for 1–2 minutes per side until opaque.','Warm the tortillas directly in the dry skillet for about 20 seconds per side.','Fill each tortilla with cabbage and shrimp; finish with avocado and lime crema.']}
];
const EXERCISES=[
{name:'Bench Press',muscle:'Chest',sets:'3–4',reps:'6–10',level:'Intermediate',cue:'Keep shoulder blades set, lower under control, press over mid-chest.',image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'},
{name:'Incline Dumbbell Press',muscle:'Chest',sets:'3',reps:'8–12',level:'Beginner',cue:'Use a moderate incline and keep wrists stacked over elbows.',image:'https://i.shgcdn.com/e73f0ceb-cffb-4f11-9805-3b752d7e85cc/-/format/auto/-/preview/3000x3000/-/quality/lighter/'},
{name:'Lat Pulldown',muscle:'Back',sets:'3–4',reps:'8–12',level:'Beginner',cue:'Drive elbows down toward your sides without swinging.',image:'https://boaforma.abril.com.br/wp-content/uploads/sites/2/2025/10/macho-de-alto-angulo-trabalhando-no-equipamento-para-armas.jpg?quality=70&strip=info'},
{name:'Barbell Row',muscle:'Back',sets:'3',reps:'6–10',level:'Intermediate',cue:'Brace your torso and row toward the lower ribs.',image:'https://boaforma.abril.com.br/wp-content/uploads/sites/2/2023/02/remada-curvada.jpg?quality=70&strip=info'},
{name:'Back Squat',muscle:'Legs',sets:'3–4',reps:'5–10',level:'Intermediate',cue:'Brace first, keep the whole foot planted, stand tall through the hips.',image:'https://repfitness.com/cdn/shop/files/DoubleBlack-Lifestyle-18-Edit.jpg?v=1686074919&width=1000'},
{name:'Romanian Deadlift',muscle:'Legs',sets:'3',reps:'8–12',level:'Intermediate',cue:'Push hips back while keeping the weight close to your legs.',image:'https://assets.orangefit.eu/1753277140-rdl_juul_3.jpg?fit=crop&h=1442&w=1920'},
{name:'Overhead Press',muscle:'Shoulders',sets:'3',reps:'6–10',level:'Intermediate',cue:'Brace and press overhead without overextending your lower back.',image:'https://images.squarespace-cdn.com/content/5bfe6866d274cb96f5021c20/1557298885756-998FOYX9GT72U56S1DDL/IMG_018.jpg?content-type=image%2Fjpeg&format=1500w'},
{name:'Lateral Raise',muscle:'Shoulders',sets:'3',reps:'12–20',level:'Beginner',cue:'Use controlled reps and stop around shoulder height.',image:'https://cdn.shopify.com/s/files/1/1214/7132/files/mt-dumbbell-lateral-raises-900x675_138ce5d0-4894-4394-b694-2a0bdd835b71_1000x.jpg?v=1706739435'},
{name:'Barbell Curl',muscle:'Arms',sets:'3',reps:'8–12',level:'Beginner',cue:'Keep elbows near your sides and avoid swinging.',image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'},
{name:'Triceps Pushdown',muscle:'Arms',sets:'3',reps:'10–15',level:'Beginner',cue:'Keep upper arms still while extending the elbows.',image:'https://thietbiphonggym.vn/image/catalog/blog/nguyen-tac-va-cac-bai-tap-voi-bap-tay-sau-1508468192883.jpg'},
{name:'Plank',muscle:'Core',sets:'3',reps:'30–60 sec',level:'Beginner',cue:'Brace as if preparing for a punch and keep hips level.',image:'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?auto=format&fit=crop&w=900&q=80'},
{name:'Hanging Leg Raise',muscle:'Core',sets:'3',reps:'8–15',level:'Intermediate',cue:'Control the swing and curl the pelvis upward at the top.',image:'https://hips.hearstapps.com/hmg-prod/images/gettyimages-482496614-1627369696.jpg'},
{name:'Push-Up',muscle:'Chest',sets:'3',reps:'8–20',level:'Beginner',cue:'Keep a straight line from head to heels and lower your chest between your hands.',image:'https://images.unsplash.com/photo-1598971639058-fab3c3109a00?auto=format&fit=crop&w=900&q=80'},
{name:'Cable Chest Fly',muscle:'Chest',sets:'3',reps:'10–15',level:'Intermediate',cue:'Keep a soft bend in the elbows and bring your hands together without shrugging.',image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'},
{name:'Seated Cable Row',muscle:'Back',sets:'3',reps:'8–12',level:'Beginner',cue:'Sit tall, lead with the elbows and pause when the handle reaches your lower ribs.',image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'},
{name:'Face Pull',muscle:'Shoulders',sets:'3',reps:'12–20',level:'Beginner',cue:'Pull toward eye level and rotate your hands back while keeping your ribs down.',image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'},
{name:'Bulgarian Split Squat',muscle:'Legs',sets:'3',reps:'8–12',level:'Intermediate',cue:'Keep most of your weight on the front leg and descend under control.',image:'https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&w=900&q=80'},
{name:'Leg Press',muscle:'Legs',sets:'3–4',reps:'10–15',level:'Beginner',cue:'Keep your lower back against the pad and stop before your hips roll upward.',image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'},
{name:'Hammer Curl',muscle:'Arms',sets:'3',reps:'10–15',level:'Beginner',cue:'Keep your palms facing inward and move only at the elbow.',image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'},
{name:'Overhead Triceps Extension',muscle:'Arms',sets:'3',reps:'10–15',level:'Intermediate',cue:'Point the elbows forward and keep the upper arms still throughout the repetition.',image:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80'},
{name:'Dead Bug',muscle:'Core',sets:'3',reps:'8–12 / side',level:'Beginner',cue:'Press your lower back into the floor and move slowly without letting it arch.',image:'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?auto=format&fit=crop&w=900&q=80'},
{name:'Cable Crunch',muscle:'Core',sets:'3',reps:'10–15',level:'Intermediate',cue:'Curl your ribs toward your pelvis instead of pulling down with your arms.',image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80'}
];

// Expand the consumer preview to 100 complete, bilingual recipes.
const RECIPE_PROTEINS=[
{en:'Chicken',es:'Pollo',ingredient:'170 g chicken breast',ingredientEs:'170 g de pechuga de pollo',cal:280,p:52,f:6,cook:'6–7 minutes per side'},
{en:'Turkey',es:'Pavo',ingredient:'170 g lean turkey',ingredientEs:'170 g de pavo magro',cal:270,p:45,f:8,cook:'8–10 minutes total'},
{en:'Lean Beef',es:'Res magra',ingredient:'170 g lean beef',ingredientEs:'170 g de res magra',cal:320,p:44,f:14,cook:'3–4 minutes per side'},
{en:'Salmon',es:'Salmón',ingredient:'170 g salmon',ingredientEs:'170 g de salmón',cal:350,p:38,f:20,cook:'10–12 minutes total'},
{en:'Shrimp',es:'Camarón',ingredient:'170 g peeled shrimp',ingredientEs:'170 g de camarón pelado',cal:190,p:40,f:3,cook:'1–2 minutes per side'},
{en:'Tuna',es:'Atún',ingredient:'140 g tuna in water',ingredientEs:'140 g de atún en agua',cal:170,p:36,f:2,cook:'2 minutes to warm'},
{en:'Crispy Tofu',es:'Tofu crujiente',ingredient:'200 g extra-firm tofu',ingredientEs:'200 g de tofu extra firme',cal:240,p:24,f:14,cook:'8–10 minutes total'},
{en:'Egg',es:'Huevo',ingredient:'2 eggs + 150 g egg whites',ingredientEs:'2 huevos + 150 g de claras',cal:250,p:31,f:11,cook:'4–5 minutes total'},
{en:'Pork Tenderloin',es:'Lomo de cerdo',ingredient:'170 g pork tenderloin',ingredientEs:'170 g de lomo de cerdo',cal:290,p:46,f:9,cook:'5–6 minutes per side'},
{en:'Lentil',es:'Lentejas',ingredient:'220 g cooked lentils',ingredientEs:'220 g de lentejas cocidas',cal:255,p:20,f:2,cook:'5 minutes to warm'}
];
const RECIPE_STYLES=[
{en:'Power Bowl',es:'Tazón energético',category:'Lunch',base:'170 g cooked brown rice',baseEs:'170 g de arroz integral cocido',veg:'150 g broccoli and carrots',vegEs:'150 g de brócoli y zanahoria',sauce:'30 g yogurt herb sauce',sauceEs:'30 g de salsa de yogur con hierbas',carbs:58,extraCal:275,image:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'},
{en:'Mediterranean Plate',es:'Plato mediterráneo',category:'Dinner',base:'180 g roasted potatoes',baseEs:'180 g de papas rostizadas',veg:'150 g cucumber and tomato salad',vegEs:'150 g de ensalada de pepino y tomate',sauce:'25 g hummus',sauceEs:'25 g de hummus',carbs:48,extraCal:250,image:'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=900&q=80'},
{en:'Street Tacos',es:'Tacos callejeros',category:'Lunch',base:'3 corn tortillas',baseEs:'3 tortillas de maíz',veg:'100 g cabbage and pico de gallo',vegEs:'100 g de col y pico de gallo',sauce:'40 g lime crema',sauceEs:'40 g de crema de limón',carbs:46,extraCal:230,image:'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=900&q=80'},
{en:'Teriyaki Bowl',es:'Tazón teriyaki',category:'Dinner',base:'170 g cooked jasmine rice',baseEs:'170 g de arroz jazmín cocido',veg:'160 g broccoli and bell pepper',vegEs:'160 g de brócoli y pimiento',sauce:'30 ml low-sugar teriyaki sauce',sauceEs:'30 ml de salsa teriyaki baja en azúcar',carbs:64,extraCal:290,image:'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=900&q=80'},
{en:'Loaded Wrap',es:'Wrap completo',category:'Lunch',base:'1 large whole-wheat tortilla',baseEs:'1 tortilla integral grande',veg:'120 g lettuce, tomato and onion',vegEs:'120 g de lechuga, tomate y cebolla',sauce:'35 g avocado yogurt sauce',sauceEs:'35 g de salsa de aguacate y yogur',carbs:44,extraCal:240,image:'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=900&q=80'},
{en:'Pasta Primavera',es:'Pasta primavera',category:'Dinner',base:'90 g dry high-protein pasta',baseEs:'90 g de pasta alta en proteína',veg:'160 g zucchini, spinach and tomatoes',vegEs:'160 g de calabacita, espinaca y tomate',sauce:'120 g tomato basil sauce',sauceEs:'120 g de salsa de tomate y albahaca',carbs:70,extraCal:330,image:'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=900&q=80'},
{en:'Quinoa Salad',es:'Ensalada de quinoa',category:'Lunch',base:'170 g cooked quinoa',baseEs:'170 g de quinoa cocida',veg:'160 g cucumber, tomato and greens',vegEs:'160 g de pepino, tomate y hojas verdes',sauce:'15 ml lemon vinaigrette',sauceEs:'15 ml de vinagreta de limón',carbs:50,extraCal:260,image:'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?auto=format&fit=crop&w=900&q=80'},
{en:'Coconut Curry',es:'Curry de coco',category:'Dinner',base:'160 g cooked basmati rice',baseEs:'160 g de arroz basmati cocido',veg:'170 g cauliflower and peas',vegEs:'170 g de coliflor y chícharos',sauce:'100 ml light coconut curry sauce',sauceEs:'100 ml de salsa ligera de curry y coco',carbs:62,extraCal:315,image:'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?auto=format&fit=crop&w=900&q=80'},
{en:'Herb Couscous',es:'Cuscús con hierbas',category:'Dinner',base:'75 g dry couscous',baseEs:'75 g de cuscús seco',veg:'150 g zucchini and peppers',vegEs:'150 g de calabacita y pimientos',sauce:'20 g parsley lemon dressing',sauceEs:'20 g de aderezo de perejil y limón',carbs:60,extraCal:275,image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=900&q=80'},
{en:'Sweet Potato Hash',es:'Salteado de camote',category:'Breakfast',base:'220 g diced sweet potato',baseEs:'220 g de camote en cubos',veg:'120 g peppers and spinach',vegEs:'120 g de pimientos y espinaca',sauce:'15 g smoky yogurt sauce',sauceEs:'15 g de salsa de yogur ahumada',carbs:52,extraCal:245,image:'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=900&q=80'}
];
const recipeImages=RECIPES.map(r=>r.image);
let recipeSequence=RECIPES.length+1;
for(const protein of RECIPE_PROTEINS){
  for(const style of RECIPE_STYLES){
    if(RECIPES.length>=100)break;
    const calories=protein.cal+style.extraCal;
    const name=`${protein.en} ${style.en}`;
    RECIPES.push({
      id:`r${recipeSequence++}`,name,category:style.category,time:'30 min',prep:'10 min',cook:'20 min',
      calories,protein:protein.p,carbs:style.carbs,fat:Math.max(7,Math.round((calories-protein.p*4-style.carbs*4)/9)),
      desc:`A balanced ${style.en.toLowerCase()} with ${protein.en.toLowerCase()}, colorful vegetables and a flavorful sauce.`,
      tip:'Prepare the base and vegetables in advance; cook the protein just before serving for the best texture.',
      image:style.image||recipeImages[RECIPES.length%recipeImages.length],
      ingredients:[protein.ingredient,style.base,style.veg,style.sauce,'1 tsp olive oil','Salt and pepper to taste'],
      steps:[
        `Pat the ${protein.en.toLowerCase()} dry, season with salt and pepper, and let it rest for 5 minutes while the pan heats.`,
        `Heat the olive oil over medium-high heat and cook the protein for ${protein.cook}, until safely cooked and browned.`,
        `Prepare ${style.base.toLowerCase()} and cook the vegetables for 4–6 minutes so they remain lightly crisp.`,
        `Build the ${style.en.toLowerCase()} with the base, vegetables and protein; add the sauce evenly and serve warm.`
      ],
      es:{
        name:`${style.es} de ${protein.es.toLowerCase()}`,
        desc:`Una opción equilibrada con ${protein.es.toLowerCase()}, vegetales coloridos y una salsa llena de sabor.`,
        tip:'Prepara la base y los vegetales con anticipación; cocina la proteína justo antes de servir para obtener mejor textura.',
        ingredients:[protein.ingredientEs,style.baseEs,style.vegEs,style.sauceEs,'1 cucharadita de aceite de oliva','Sal y pimienta al gusto'],
        steps:[
          `Seca ${protein.es.toLowerCase()}, sazona con sal y pimienta y deja reposar 5 minutos mientras se calienta la sartén.`,
          `Calienta el aceite a fuego medio-alto y cocina la proteína durante ${protein.cook.replace('minutes','minutos').replace('per side','por lado').replace('total','en total')}, hasta que esté bien cocida y dorada.`,
          `Prepara ${style.baseEs.toLowerCase()} y cocina los vegetales de 4 a 6 minutos para conservarlos ligeramente crujientes.`,
          `Arma el plato con la base, los vegetales y la proteína; distribuye la salsa y sirve caliente.`
        ]
      }
    });
  }
}

// Expand the movement library to 100 bilingual exercises.
const EXERCISE_SEEDS={
Chest:[['Dumbbell Floor Press','Press con mancuernas en el piso'],['Machine Chest Press','Press de pecho en máquina'],['Decline Push-Up','Flexión declinada'],['Kneeling Push-Up','Flexión con rodillas'],['Close-Grip Push-Up','Flexión con agarre cerrado'],['Incline Push-Up','Flexión inclinada'],['Single-Arm Cable Press','Press unilateral en polea'],['Dumbbell Pullover','Pullover con mancuerna'],['Pec Deck Fly','Apertura en peck deck'],['Paused Bench Press','Press de banca con pausa'],['Tempo Push-Up','Flexión con tempo'],['Landmine Press','Press landmine'],['Svend Press','Press Svend'],['Resistance-Band Fly','Apertura con banda']],
Back:[['Assisted Pull-Up','Dominada asistida'],['Pull-Up','Dominada'],['Chin-Up','Dominada supina'],['Single-Arm Dumbbell Row','Remo con mancuerna a una mano'],['Chest-Supported Row','Remo con pecho apoyado'],['T-Bar Row','Remo con barra T'],['Straight-Arm Pulldown','Jalón con brazos rectos'],['Machine High Row','Remo alto en máquina'],['Resistance-Band Row','Remo con banda'],['Inverted Row','Remo invertido'],['Meadows Row','Remo Meadows'],['Wide-Grip Pulldown','Jalón con agarre ancho'],['Neutral-Grip Pulldown','Jalón con agarre neutro'],['Dumbbell Shrug','Encogimiento con mancuernas']],
Legs:[['Goblet Squat','Sentadilla goblet'],['Front Squat','Sentadilla frontal'],['Walking Lunge','Desplante caminando'],['Reverse Lunge','Desplante inverso'],['Step-Up','Subida al banco'],['Hip Thrust','Empuje de cadera'],['Glute Bridge','Puente de glúteos'],['Leg Extension','Extensión de piernas'],['Lying Leg Curl','Curl femoral acostado'],['Seated Leg Curl','Curl femoral sentado'],['Standing Calf Raise','Elevación de pantorrilla de pie'],['Seated Calf Raise','Elevación de pantorrilla sentado'],['Sumo Deadlift','Peso muerto sumo'],['Hack Squat','Sentadilla hack'],['Cable Pull-Through','Jalón entre piernas en polea']],
Shoulders:[['Arnold Press','Press Arnold'],['Dumbbell Shoulder Press','Press de hombro con mancuernas'],['Machine Shoulder Press','Press de hombro en máquina'],['Cable Lateral Raise','Elevación lateral en polea'],['Rear Delt Fly','Apertura posterior'],['Reverse Pec Deck','Peck deck inverso'],['Front Raise','Elevación frontal'],['Upright Row','Remo al mentón'],['Band Pull-Apart','Apertura con banda'],['Dumbbell Y-Raise','Elevación en Y'],['Single-Arm Landmine Press','Press landmine unilateral'],['Cuban Rotation','Rotación cubana'],['Wall Slide','Deslizamiento en pared'],['Scaption Raise','Elevación en plano escapular']],
Arms:[['Dumbbell Curl','Curl con mancuernas'],['Incline Dumbbell Curl','Curl inclinado con mancuernas'],['Cable Curl','Curl en polea'],['Preacher Curl','Curl predicador'],['Concentration Curl','Curl concentrado'],['Reverse Curl','Curl inverso'],['EZ-Bar Curl','Curl con barra EZ'],['Rope Pushdown','Extensión con cuerda'],['Skull Crusher','Rompecráneos'],['Close-Grip Bench Press','Press de banca cerrado'],['Triceps Kickback','Patada de tríceps'],['Bench Dip','Fondo en banco'],['Single-Arm Pushdown','Extensión unilateral en polea'],['Cross-Body Hammer Curl','Curl martillo cruzado']],
Core:[['Bird Dog','Perro de caza'],['Side Plank','Plancha lateral'],['Pallof Press','Press Pallof'],['Ab Wheel Rollout','Rueda abdominal'],['Reverse Crunch','Crunch inverso'],['Bicycle Crunch','Crunch bicicleta'],['Mountain Climber','Escalador'],['Russian Twist','Giro ruso'],['Hollow Body Hold','Posición hueca'],['Farmer Carry','Caminata del granjero'],['Suitcase Carry','Caminata con maleta'],['Plank Shoulder Tap','Toque de hombro en plancha'],['Heel Tap','Toque de talón'],['Knee Raise','Elevación de rodillas']]
};
const exerciseImages={Chest:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80',Back:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80',Legs:'https://images.unsplash.com/photo-1434682881908-b43d0467b798?auto=format&fit=crop&w=900&q=80',Shoulders:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=900&q=80',Arms:'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=900&q=80',Core:'https://images.unsplash.com/photo-1566241142559-40e1dab266c6?auto=format&fit=crop&w=900&q=80'};
const muscleCue={
Chest:['Keep your shoulder blades stable and control the lowering phase.','Mantén estables los omóplatos y controla la fase de descenso.'],
Back:['Brace your torso, lead with the elbows and avoid using momentum.','Mantén firme el torso, guía con los codos y evita usar impulso.'],
Legs:['Keep the whole foot planted, brace your core and move through a controlled range.','Mantén todo el pie apoyado, activa el abdomen y usa un rango controlado.'],
Shoulders:['Keep your ribs down and move the weight without shrugging.','Mantén las costillas controladas y mueve el peso sin elevar los hombros.'],
Arms:['Keep the upper arm still and complete every repetition without swinging.','Mantén inmóvil la parte superior del brazo y completa cada repetición sin balancearte.'],
Core:['Breathe out, brace firmly and keep your spine in a controlled position.','Exhala, activa firmemente el abdomen y mantén la columna en una posición controlada.']
};
const knownExercises=new Set(EXERCISES.map(x=>x.name));
for(const [muscle,movements] of Object.entries(EXERCISE_SEEDS)){
  for(const [name,nameEs] of movements){
    if(EXERCISES.length>=100)break;
    if(knownExercises.has(name))continue;
    EXERCISES.push({name,nameEs,muscle,sets:muscle==='Core'?'3':'3–4',reps:muscle==='Core'?'10–16':'8–15',repsEs:muscle==='Core'?'10–16':'8–15',level:EXERCISES.length%3===0?'Intermediate':'Beginner',cue:muscleCue[muscle][0],cueEs:muscleCue[muscle][1],image:exerciseImages[muscle]});
    knownExercises.add(name);
  }
}
